### ISSUE TITLE
Gradle install problem 

### ISSUE THREAD

**Issue by shohan4556** [nraboy/ubuntu-ionic-installer#11]
when I run the shell after sometimes it just  stoped 
here is the screen shot 
please let me know where is the problem. 

![ionic](https://cloud.githubusercontent.com/assets/8347571/12645696/f9cf1fec-c5f5-11e5-8a5e-671fc8a1114a.png)

**Comment by nraboy** [comment]
How long did you wait before canceling?  The script takes a variable amount of time depending on your internet, system specs, ect.
