### ISSUE TITLE
New Versions of Android SDK and NodeJS

### ISSUE THREAD

**Issue by mjraval** [nraboy/ubuntu-ionic-installer#4]
Hi,
   Thanks for the Excellent Script and very informative video. Just to mentions, you might want to update the download links to the latest version of both Android SDK and NodeJS

Thanks.

Really appreciate you taking your time and give this script out to everyone.

**Comment by nraboy** [comment]
Updating the links is on my agenda.  Thanks for the reminder :-)

**Comment by nraboy** [comment]
Updated.

Thanks!
