### ISSUE TITLE
Resume Download

### ISSUE THREAD

**Issue by nueko** [nraboy/ubuntu-ionic-installer#8]
I suggest using 

``` bash
wget -c [url]
```

so download will resume when failed

**Comment by nraboy** [comment]
Thanks!

I will commit the change as time permits.

**Comment by nraboy** [comment]
Added to https://github.com/nraboy/ubuntu-ionic-installer/commit/5e16ab1ea69a0372ac45b980284eb4cdef45a12a

Thanks for the recommendation!
