### ISSUE TITLE
Outdated version of NodeJS?

### ISSUE THREAD

**Issue by Zerokami** [nraboy/ubuntu-ionic-installer#9]
When I ran the script it downloaded NodeJS V0.12.2. Is this version production ready. I followed the link http://nodejs.org/dist/ and it shows v5.x . I'm not really sure if the script is downloading an outdated version.

**Comment by nraboy** [comment]
0.12 is still a preferred version by many.  4.x was a merge with another fork of the Node.js project.

You should be fine with 0.12.  It is the version I use.
